// import "./globals.css";
import "@/style/globals.css"
import Footer from "@/components/Footer";
// import Navbar from "@/components/NavbarBar";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Urbania Realty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
