import Footer from "@/components/Footer";
import "./globals.css";

export const metadata = {
  title: "Urbania Realty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
