import "@/style/globals.css"
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Urbania Realty",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // default favicon
    shortcut: "/favicon.ico", // optional
    apple: "/favicon.png", // optional, for iOS devices
    other: [
      {
        rel: "icon",
        url: "/favicon.svg",
        type: "image/svg+xml",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
